kind: "Template"
apiVersion: "v1"
metadata:
  name: "deployment-template"
labels:
  template: "deployment-template"
parameters:
  - name: "TAG"
    description: "tag of the deployment"
    value: develop
    required: true
  - name: "STORAGE_CLASS"
    description: "volume of the deployment"
    value: "gp2"
    required: false
  - name: "MONGO_REPOSITORY"
    description: "mongodb container repository"
    value: "quay.io/arbhatta/mongo:4.2.8"
    required: false
  - name: "MANAGER_REPOSITORY"
    description: "SPAship manager repository"
    value: "quay.io/spaship/spaship-manager"
  - name: "OPERATOR_REPOSITORY"
    description: "SPAship operator repository"
    value: "quay.io/arbhatta/operator"
    required: false
  - name: "UI_REPOSITORY"
    description: "SPAship UI repository"
    value: "quay.io/spaship/spaship-ui"
    required: false
  - name: "API_URL"
    description: "api url for spaship orchestrator"
    value: "localhost:3000"
    required: true
  - name: "UI_MEMORY_LIMIT"
    description: "memory limit for spaship ui"
    value: "512Mi"
    required: true
  - name: "DOMAIN"
    required: true
objects:
  - kind: Service
    apiVersion: v1
    metadata:
      name: operator-service
      labels:
        app.kubernetes.io/name: operator
        app.kubernetes.io/instance: operator
        app.kubernetes.io/version: 1.0.0
        app.kubernetes.io/managed-by: spaship
    spec:
      type: ClusterIP
      clusterIP: None
      ports:
        - port: 8080
          targetPort: http
          protocol: TCP
          name: http
      selector:
        app.kubernetes.io/name: operator
        app.kubernetes.io/instance: operator
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: operator-config
      labels:
        app.kubernetes.io/name: operator
        app.kubernetes.io/instance: operator
        app.kubernetes.io/version: 1.0.0
        app.kubernetes.io/managed-by: spaship
    data:
      OPERATOR_EVENT_BUS_ADDRESS: spa-ops-event-channel
      OPERATOR_DOMAIN_NAME: ${DOMAIN}
  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      name: operator
      labels:
        app.kubernetes.io/name: operator
        app.kubernetes.io/instance: operator
        app.kubernetes.io/version: 1.0.0
        app.kubernetes.io/managed-by: spaship
    spec:
      selector:
        matchLabels:
          app.kubernetes.io/name: operator
          app.kubernetes.io/instance: operator
      template:
        metadata:
          labels:
            app.kubernetes.io/name: operator
            app.kubernetes.io/instance: operator
        spec:
          serviceAccountName: light-cd
          securityContext:
            {}
          containers:
            - name: operator
              securityContext:
                {}
              image: "${OPERATOR_REPOSITORY}:${TAG}"
              envFrom:
                - configMapRef:
                    name: operator-config
              imagePullPolicy: Always
              ports:
                - name: http
                  containerPort: 8080
                  protocol: TCP
              livenessProbe:
                tcpSocket:
                  port: http
                initialDelaySeconds: 30
                periodSeconds: 10
              readinessProbe:
                tcpSocket:
                  port: http
                initialDelaySeconds: 30
                periodSeconds: 10
              resources:
                limits:
                  cpu: 600m
                  memory: 512Mi
                requests:
                  cpu: 300m
                  memory: 256Mi