apiVersion: v1
kind: Service
metadata:
  name: light-cd
  labels:
    app.kubernetes.io/name: light-cd
    app.kubernetes.io/instance: light-cd
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: arbhatta
spec:
  type: ClusterIP
  ports:
    - port: 8080
      name: http
  selector:
    app.kubernetes.io/name: light-cd
    app.kubernetes.io/instance: light-cd