kind: ConfigMap
apiVersion: v1
metadata:
  name: light-cd-config
data:
  APPLICATION_K8S_NAMESPACE: {{ .Values.app.namespace }}
  VALIDATION_TRIGGER_TAG: {{ .Values.app.environment | squote  }}
  TEMPLATE_STORAGE_PARAM_VALUE: {{ .Values.app.storageclass }}
  TEMPLATE_API_URL_PARAM_VALUE: http://{{ .Values.app.instance }}.spaship.api.{{ .Values.app.domain }}/api/v1
  TEMPLATE_UI_MEMORY_LIMIT: {{ .Values.app.uimemory }}
  TEMPLATE_DOMAIN: {{ .Values.app.domain }}
  APP_INSTANCE: {{ .Values.app.instance }}
  APP_SECURITY_ALLOWED_USERS: "{{ .Values.app.users }}"
  APP_SECURITY_HEADER: "apiKey"
  APP_SECURITY_KEYSIZE: "512"
  APP_AUTH_ENABLED: "{{ .Values.app.auth }}"
  RSA_PUBLIC_KEY: {{ .Values.app.publickey }}
  RSA_PRIVATE_KEY: {{ .Values.app.privatekey }}
